server:
  port: 8080
  tomcat:
    threads:
      # tomcat最大线程数，默认为200, 4核8G内存，4*200
      max: 800
      # Tomcat最小线程数，默认值10
      min-spare: 30
    #最大连接数, 默认8192
    max-connections: 8192
    # 连接超时,默认60s
    connection-timeout: 30s
    #最大等待队列长度, 默认100  当服务器达到最大连接数max-connections时，仍可以接收的最大请求数。
    accept-count: 300
